# Generated by Django 5.1 on 2024-08-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_and_paids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'completed'), (2, 'rejected')], default=1),
        ),
    ]
