# Generated by Django 5.1 on 2024-08-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_and_paids', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='outstanding',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
